version: '3.7'

services:
    database :
        image: postgres
        container_name: database_ignite
        restart: always
        ports: 
            - 5432:5432
        environment: 
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=ignite
            - POSTGRES_DB=rentx
        volumes:
            - pgdata:/data/postgres
    app :
        build: .
        container_name: rentx
        ports: 
            - 3330:3330
        volumes:
            - .C:\Users\User\Desktop\dockerConfig
        links :
            - database
        depends_on :
            - database
volumes :
        pgdata :
            driver : local